services:
  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
 
  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd_node2
    restart: always
    network_mode: host
    volumes:
      - "./etcd:/run/etcd.data"
    command: "sh -c 'exec etcd'"
    extra_hosts:
      - "pg_node1:192.168.0.123"
      - "pg_node2:192.168.0.124"
      - "etcd_node1:192.168.0.123"
      - "etcd_node2:192.168.0.124"
    healthcheck:
      test: ["CMD-SHELL", "etcdctl", "--endpoints='etcd_node1'", "endpoint", "health"]
      interval: 10s
      timeout: 10s
      retries: 12
    environment:
      ETCD_DATA_DIR: /run/etcd.data
      ETCD_INITIAL_CLUSTER: etcd_node1=http://etcd_node1:2380,etcd_node2=http://etcd_node2:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-token.local.net
      ETCD_NAME: etcd_node2
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd_node1:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_node1:2379
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_LOG_OUTPUTS: stdout

